# Generated by Django 3.2.6 on 2021-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('priority_no', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('duedate', models.DateTimeField()),
            ],
        ),
    ]
